const data = [
  {
    patient: 1,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 999,
    mites_bl: 8.75,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 2,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 2.75,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 3,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: 999,
    mites_bl: 1.75,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 4,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 999,
    mites_bl: 2.75,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 5,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 1.5,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 6,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: 999,
    mites_bl: 2.25,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 7,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 999,
    mites_bl: 3.25,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 8,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 3,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 9,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: 999,
    mites_bl: 2.25,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 10,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 1.5,
    mites_day43: 999,
    erythema_bl: 3,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 11,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 12,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 13,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 14,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 15,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 16,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 17,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 18,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 19,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 20,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 21,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 22,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 23,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 24,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 25,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 26,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 27,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 28,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 29,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 30,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 31,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 6.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 32,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 33,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 34,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 7,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 35,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 7.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 36,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 37,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 38,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 39,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 8.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 40,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 8.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 41,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 8.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 42,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 43,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 44,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 45,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 46,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 47,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 48,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 49,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 50,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 51,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 52,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 53,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 54,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 55,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 56,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 57,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 58,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 59,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 60,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 61,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 62,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 63,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 64,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 65,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 66,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 67,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 68,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 69,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 70,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 71,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 72,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 6.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 73,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 74,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 75,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 7,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 76,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 7.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 77,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 78,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 79,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 80,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 8.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 81,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 8.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 82,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 8.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 83,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 84,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 85,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 86,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 87,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 88,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 89,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 90,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 91,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 92,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 93,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 94,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 95,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 96,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 97,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 98,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 99,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 100,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 101,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 102,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 103,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 104,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 4,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 105,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 106,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 107,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 108,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 109,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 110,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 111,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 112,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 6,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 113,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 6.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 114,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 115,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 116,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 117,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 0,
    mites_bl: 7.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 118,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 119,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 120,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 121,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 122,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 123,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 124,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 125,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 126,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 127,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 128,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 129,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 130,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 131,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 132,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 133,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 134,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 135,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 136,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 137,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 138,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 139,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 140,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 141,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 142,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 143,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 144,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 145,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 146,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 147,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 148,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 149,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 150,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 151,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 152,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 153,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 154,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 6.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 155,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 156,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 157,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 158,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 7.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 159,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 160,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 161,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 162,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 163,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 164,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 165,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 166,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 167,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 168,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 169,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 170,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 171,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 172,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 173,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 174,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 175,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 176,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 177,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 178,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 179,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 180,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 181,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 182,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 183,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 184,
    group: "TP03",
    age: 55,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 185,
    group: "TP03",
    age: 70,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 186,
    group: "TP03",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 187,
    group: "TP03",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 188,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 189,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 190,
    group: "TP03",
    age: 88,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 191,
    group: "TP03",
    age: 18,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 192,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 193,
    group: "TP03",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 194,
    group: "TP03",
    age: 42,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 195,
    group: "TP03",
    age: 72,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 6.25,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 196,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 197,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 198,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 199,
    group: "TP03",
    age: 85,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 7.25,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 200,
    group: "TP03",
    age: 80,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.75,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 201,
    group: "TP03",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 202,
    group: "TP03",
    age: 64,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.75,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 203,
    group: "TP03",
    age: 63,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 204,
    group: "TP03",
    age: 87,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 205,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 999,
    mites_bl: 3,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 206,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 3,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 207,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: 999,
    mites_bl: 2,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 208,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 999,
    mites_bl: 3,
    mites_day43: 999,
    erythema_bl: 1,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 209,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 2,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 210,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: 999,
    mites_bl: 4,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 211,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 999,
    mites_bl: 5.5,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 212,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: 999,
    mites_bl: 3,
    mites_day43: 999,
    erythema_bl: 2,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 213,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: 999,
    mites_bl: 6,
    mites_day43: 999,
    erythema_bl: 3,
    erythema_day43: 999,
    completed: 0,
  },
  {
    patient: 214,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 0.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 215,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 216,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 217,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 218,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 219,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 220,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 221,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 222,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 223,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 224,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 225,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 226,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 5.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 227,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 228,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 229,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 230,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 231,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 232,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 8.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 233,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 234,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 235,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 236,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 237,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 238,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: 0,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 239,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 240,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 241,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 242,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 243,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 244,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 245,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 246,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 4.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 247,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 6.75,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 248,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 10,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 249,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 0.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 250,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 251,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 252,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 253,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 254,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 255,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 256,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 257,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 258,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 259,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 260,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 261,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 5.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 262,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 263,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 264,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 265,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 266,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 267,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 268,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 269,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 270,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 271,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 272,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 273,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 274,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 2,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 275,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 276,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 277,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 278,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 279,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 280,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 281,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 4.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 282,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 6.75,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 283,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 284,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 0.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 285,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 286,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 287,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 288,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 289,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 290,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 291,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 292,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 293,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 294,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 295,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 296,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 5.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 297,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 298,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 299,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 300,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 301,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 302,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 303,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 304,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 305,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 306,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 307,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 308,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 309,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 1,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 310,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 311,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 312,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 313,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 314,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 315,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 316,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 4.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 317,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 6.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 318,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 319,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 0.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 320,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 321,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 322,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 323,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 324,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 325,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 326,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 327,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 328,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 329,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 330,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 331,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 5.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 332,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 333,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 334,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 335,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 336,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 337,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 338,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 339,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 340,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 341,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 342,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 343,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 344,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 345,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 346,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 347,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 348,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 349,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 3,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 350,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 351,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 4.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 352,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 6.75,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 353,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 354,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 0.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 355,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 356,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 357,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 358,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 359,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 360,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 361,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 362,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 363,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 364,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 365,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 366,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 5.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 367,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 368,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 369,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 370,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 371,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 372,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 373,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 374,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 375,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 376,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 377,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 378,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 379,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 380,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 381,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 382,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 383,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 384,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 385,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 386,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 4.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 387,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 6.75,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 388,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 389,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 0.5,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 390,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 391,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 392,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 393,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 394,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 1,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 395,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 396,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 397,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 0,
    erythema_bl: 2,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 398,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 399,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 400,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 4,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 401,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 5.5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 402,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 403,
    group: "VEH",
    age: 24,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 6,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 404,
    group: "VEH",
    age: 45,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 405,
    group: "VEH",
    age: 52,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 7,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 406,
    group: "VEH",
    age: 60,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 407,
    group: "VEH",
    age: 76,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 8.25,
    mites_day43: 0,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 408,
    group: "VEH",
    age: 77,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.5,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 409,
    group: "VEH",
    age: 79,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 410,
    group: "VEH",
    age: 84,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 2.25,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 0,
    completed: 1,
  },
  {
    patient: 411,
    group: "VEH",
    age: 89,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
  {
    patient: 412,
    group: "VEH",
    age: 65,
    diagnosis: "",
    collarettes_grade_bb: 4,
    collarettes_grade_day43: null,
    mites_bl: 3.25,
    mites_day43: 2,
    erythema_bl: 3,
    erythema_day43: 2,
    completed: 1,
  },
];
